services:

  GP\Oxid\Skeleton\Command\Component:
    tags:
      - { name: console.command, command: 'gp:skeleton:component' }
    autowire: true
    public: true

  GP\Oxid\Skeleton\Command\Module:
    tags:
      - { name: console.command, command: 'gp:skeleton:module' }
    autowire: true
    public: true